filldata:
	ipython -i -c 'from schema.schema import *; (h5file, group, genotypes_table) = create_testfile(); filldata(h5file)'

connect:
	ipython -i -c 'from schema.schema import *; (h5file, group, genotypes_table) = create_testfile()'


